#!/bin/bash

function test {
  local file=${1-all.test.rb}
  bundle exec ruby $file
}

function lint {
  bundle exec rubocop "$@"
}

function build {
  lint
  test
}

function acquisition_tracker {
  be ruby main.rb "$@"
}

function be {
  bundle exec "$@"
}

if [[ $# -gt 0 ]]; then
  eval "$1" "${@:2}"
fi
