#!/bin/bash

function test {
  local file=${1-all.test.rb}
  bundle exec ruby $file
}

function lint {
  bundle exec rubocop "$@"
}

function build {
  lint
  test
}

function acquisition_tracker {
  be ruby main.rb "$@"
}

function be {
  bundle exec "$@"
}

function repl {
  if [[ $1 ]]; then
    export AT_DEV=true
  fi
  bundle exec pry -r './main.rb' -e 'include AcquisitionTracker; Commands.hydrate Journal.load_journal_entries;nil'
}

if [[ $# -gt 0 ]]; then
  eval "$1" "${@:2}"
fi
