#!/bin/bash

function test {
  bundle exec ruby all.test.rb
}

function lint {
  bundle exec rubocop
}

function build {
  lint
  test
}

function aquisition_tracker {
  be ruby main.rb "$@"
}

function be {
  bundle exec "$@"
}

if [[ $# -gt 0 ]]; then
  eval "$1" "${@:2}"
fi
